name: Release latest version

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to release branch
        run: |
          git checkout release

      - name: Delete everything
        run: |
          git rm -rf .
          git commit -m "Clear release branch"

      - name: Pull latest changes from master branch
        run: |
          git checkout master
          git pull origin master
          git checkout release
          git merge master --allow-unrelated-histories -X theirs

      - name: Remove .gitignore and .github
        run: |
          git rm -r --cached .gitignore .github

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "New release" || echo "No changes to commit"
          git push origin release